.github/workflows/main.yml
> #15 
- 워크플로우 테스트를 위한 수동 실행 기능 추가
=> feat: 워크플로우 수동 실행 기능 추가

.github/workflows/commit-notifier.yml
> #20 
- 의도치 않은 문자 및 공백 방지 코드 추가
=> fix: 2차 커밋 인증 워크 플로우 에러 수정

.github/workflows/commit-notifier.yml
> #20 
- 워크플로우 sh 환경에서의 연관 배열 로직 에러로 case 문으로 수정
=> fix: 3차 커밋 인증 워크 플로우 에러 수정

.github/workflows/commit-notifier.yml
> #20
- 작업자, 커밋 카운팅 방식 수정
- 개별 디코 채널 및 레포지토리에서 테스트 완료
=> fix: 5차 커밋 인증 워크 플로우 에러 수정

.github/workflows/commit-notifier.yml
> closed #27 
- 알림 메시지 형식 수정
- 작업자 예외처리 추가
- 웹 훅 수정
=> chore: 커밋 인증 워크 플로우 디테일 수정

.github/workflows/commit-notifier.yml
=> chore: 2차 커밋 인증 워크 플로우 디테일 수정

.github/workflows/commit-notifier.yml
> address #27 
- 기준 시간 한국 추가
- 디버깅 코드 추가
- 커밋 저장 방식 수정
- 웹 훅 수정
=> :wrench: chore: 커밋 저장 방식 및 웹 훅 수정

package-lock.json, package.json, src/app/layout.tsx, src/lib/axiosInstance.ts, src/util/toast.ts
> closes #30 
- axios 인스턴스 함수 추가
- 공통 에러 처리를 위한 리스폰스 인터셉터 추가
- 일관적인 UI를 위한 react-toastify 라이브러리 추가
- 토스트 커스텀 파일 추가
- 토스트 전역 설정 추가
=> feat: axios 인스턴스 추가

.github/workflows/commit-notifier.yml
> addresses #27 
- 커밋 카운트 기준 날짜 수정
- 한국 기준 전날 자정 ~ 실행 1초전까지
=> chore: 3차 커밋 인증 워크 플로우 디테일 수정

eslint.config.mjs, package-lock.json, package.json
> addresses #46 
- react 플러그인 재정의 에러 수정
- 중복 규칙 제거
- package.json 내 모듈 타입 명시 추가
=> fix: ESLint 에러 수정

.github/workflows/commit-notifier.yml, webhook.env
> closes #49 
- 웹 훅 보안 이슈 😥로 환경 변수 처리
- 기존 커밋 환경 변수 저장 방식 변경
=> chore: 커밋 인증 워크 플로우 환경 변수 처리 변경

.gitignore
> addresses #49 
- gitignore 환경 변수 규칙 추가
- 기존 웹 훅 변수 파일 삭제...
- 웹 훅 또 수정...
=> chore: 3차 커밋 인증 워크 플로우 환경 변수 처리 변경

.vscode/settings.json, src/app/[teamid]/tasklist/page.tsx, src/feature/[teamid]/tasklist/TaskItem.tsx
#40 
- 할일 리스트 페이지 1차 구현
- ui 위주, 데이터연결 x
=> ✨ feat: 할일 리스트 페이지 ui 구현

src/hook/useFiltering.ts
> close #9 
필터링 개발.
고급 프로젝트에서는 원하는 데이터를 필터링을 해주며 해당 필터링된 목록이 드롭다운화되어 리턴해주는 필터링 컴포넌트였다면, 이번에는 use hook으로 바꾸어 해당 필터링 hook에 필터링할 전체 데이터와, 필터링시킬 단어를 전달하면 배열로 리턴해주는 함수를 제작.
실시간으로 필터링해주기 위해서는 input의 onChange이벤트로 e.target.value를 필터링 훅의 두 번째 인자로 넘겨주면 된다.
예시 코드
```typescript
import useFiltering from "@/hook/useFiltering";
const Home = () => {
const { filteredData } = useFiltering(['오렌지', '사과', '바나나'], 'ㄱ');
return (
<div className="min-h-screen·grid-rows-[20px_1fr_20px]·items-center·justify-items-center·gap-16·p-8·pb-20·font-[family-name:var(--font-geist-sans)]·sm:p-20">
<div>
<h2 className="text-2xl font-bold">Filtered Data</h2>
<ul>
{filteredData.map((item, index) => (
<li key={index}>{item}</li>
))}
</ul>
</div>
</div>
);
};
export default Home;
```
=> ✨ feat: 필터링 1차 개발

tailwind.config.ts
close #63 
- 테일윈드 세팅에 주소오류가 있어 이부분을 수정함
```
content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
```
=> 🐛 fix: tailwind.config 경로오류 수정

eslint.config.mjs, src/shared/header/Header.tsx
close #42 
- 헤더 틀 개발
- eslint '@typescript-eslint/no-unused-vars':  옵션 error -> warn 수정 (테스트를 위해 임시 변수를 만들어두고 싶은데 에러때문에 merge가 안되니 불편함)
헤더가 생각보다 설계가 굉장히 필요하군요. 쿼리별로 헤더가 다르고 로그인 여부에 따라도 다르고 반응형 디바이스별로도 다르고 해서 시간이 생각보다 걸릴듯!
=> feat: 헤더 1차 개발

src/shared/input.tsx
> close #3
- onChange, onBlur, type 등 이전에 props 처리했던 값 html 처리 (역할 분리 위해서)
- 사용 예시 (리액트 훅 폼 import)
``` 
<Input
{...register('email', {
required: '이메일을 입력해주세요.',
onChange: (e) => {
const value = e.target.value;
if (value.length < 1) {
setError('email', {
type: 'manual',
message: '이메일을 입력해주세요.',
});
} else {
clearErrors('email');
}
},
onBlur: (e) => {
const value = e.target.value;
if (!value) {
setError('email', {
type: 'manual',
message: '이메일을 입력해주세요.',
});
} else {
clearErrors('email');
}
},
})}
나머지 props 처리
/>;
```
처럼 onBlur, onChange 등 처리 해주시면 됩니다. 
- 문제점: 에러 메세지 발생시 border-bottom 처리 어떻게 할 것인지
=> ♻️ refactor: props  html Element 처리

package-lock.json, package.json, src/app/[teamid]/tasklist/page.tsx, src/feature/[teamid]/tasklist/TaskItem.tsx, src/feature/[teamid]/tasklist/TaskListPage.tsx, tailwind.config.ts
=> feat: 할일 리스트 페이지 2차 개발

.github/workflows/commit-notifier.yml
> 노이슈
- 보안 처리 이전으로 롤백
- 추가 수정 없이 진행, 에러 시 삭제
=> chore: 커밋 인증 워크 플로우 롤백

.github/workflows/commit-notifier.yml
=> chore: 2차 커밋 인증 워크 플로우 롤백

package-lock.json, package.json, src/app/[teamid]/tasklist/page.tsx, src/feature/[teamid]/tasklist/TaskItem.tsx, src/feature/[teamid]/tasklist/TaskListPage.tsx, src/shared/myCalendar/myCalendar.css, src/shared/myCalendar/myCalendar.tsx, tailwind.config.ts
#54 
- 캘린더 컴포넌트 개발(react-calendar/dayjs 이용)
캘린더는 react-calendar, 날짜는 dayjs 패키지 이용
데이터 포매팅 및 스타일 적용 완료
언어는 en 설정, 달력은 클라이언트에서 new Date()로 생성된 일시를 기준으로 펼쳐집니다
테두리 상시 있음
선택된 날짜 스타일(녹색), 호버된 날짜 스타일(회색) 있음
'Febuary 2025' 부분 클릭시 월선택, 년선택 뷰로 바뀌는 기능이 있어 막아야합니다
=> feat: 캘린더 컴포넌트 개발

src/app/login/page.tsx, src/shared/input/input.tsx
> close #93 
- 내부 postSignIn 은 이후에 api 연결하고 지울 예정입니다.
=> feat: 로그인 페이지 2차 개발

src/app/login/page.tsx, src/store/userAtom.tsx
> close #96
- jotai 로 store 만들어서 accessToken 이랑 user 정보 저장해둘 수있게 해두었습니다.
- 사용은 ``` import {useAtom} from 'jotai'; import { accessTokenAtom, userAtom } from '@/store/userAtom'; ``` 하셔서 쓰시면 되는데 약간 오류가 있는 것 같아서 수정할 예정입니다:)...
- 아직 나머지 input props 나 내부 구조는 수정 안했습니다! api 변경도 그대로입니다
=> feat:유저 정보 저장

src/app/globals.css, tailwind.config.ts
> closes #83
테일윈드 설정 수정했습니다.
- 중단점 수정
데스크탑 퍼스트 기준으로 각 중단점 수정
- 컬러 섹션 수정
피그마 컬러 그대로 옮긴 후, 테마 컬러만 global과 함께 바꿨습니다.
라이트 모드 기준으로 진행하기 때문에 일부 섹션에서 불필요한 변수가 있을 수 있습니다.
필요 시 각 섹션에 맞게 추가하시거나, 수정해주세요. 
- 폰트 사이즈 기준 변경 및 변수명 수정
2lg가 어색하고, 16px이 기본 폰트 사이즈라고 판단하여 2xs를 시작으로 변수명을 수정했습니다.
반응형보다 기본 스타일링을 먼저 작업하셨을 것 같아 기존 컬러 섹션은 그대로 두었습니다.
이후 수정이 완료되면 삭제 예정입니다.
=> chore: 테일윈드 설정 수정

src/hook/useDevice.ts
=> fix: use client 추가

src/app/login/page.tsx, src/app/myhistory/page.tsx, src/lib/axiosInstance.ts
> close #117
- 10초에 한번씩 리프레시 토큰 갱신됩니다(초 바꿀 예정)
- 이전에 accessToken이 존재하면 자동으로 myhistory 페이지로 라우팅되도록 설정했는데 쿠키 유효 시간이 지나도 세션스토리지는 지워지지 않아서 계속 라우팅이 되는 문제가 발생했습니다. 그래서 일단 라우팅은 지워두었습니다.
- 로그인 하시면 헤더에서 authorization 값 확인하실 수 있습니다.
=> feat: refreshToken hook 확인 및 헤더 내 accessToken 추가
